### ISSUE TITLE
Unable to run tool as shown in readme

### ISSUE THREAD

**Issue by naheller** [koenvanzuijlen/giantbomb-show-dl#9]
Hello, thanks for your work! I copy pasted your example command (adding my own API key):

```
npx giantbomb-show-dl --api_key <YOUR_API_KEY> --show "Unprofessional Fridays" --dir "~/Downloads/GiantBomb"
```

And received the following error:

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from /usr/local/lib/node_modules/giantbomb-show-dl/dist/api.js
    at packageResolve (internal/modules/esm/resolve.js:650:9)
    at moduleResolve (internal/modules/esm/resolve.js:691:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
    at link (internal/modules/esm/module_job.js:71:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

My Node version is `v14.17.2`. Your advice is appreciated!

**Comment by naheller** [comment]
Update: the tool works after updating Node to `v16.15.1`. I'm not sure if it's relevant, but the `got` [readme](https://github.com/sindresorhus/got#comparison) states that HTTP/2 support requires Node.js 15.10.0 or above.

**Comment by koenvanzuijlen** [comment]
Indeed at least Node version 15 is currently required. I added the minimum required version to the instructions, but there is no way to check it at runtime as the crash happens before that.
